name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  RESULT_HASH: hello

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/checkout@v2

    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name : Get git hash
      run : | 
    - name : getApkName
      id : apkName
      run : |
        apkPath=$(find app/build/outputs/apk/debug/*.apk)
        echo $apkPath
      env : 
        APK_PATH: $apkPath
    
    - name: ch1
      run:  |
        echo ${{ steps.apkName.env.APK_PATH }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ${{ steps.apkName.env.APK_PATH }}
   
