name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  RESULT_HASH: hello

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ch1
      run:  |
        RESULT=$(git rev-parse --short HEAD)
        echo $RESULT
        $RESULT_HASH: $RESULT
    - name: ch2
      run:  |
        echo $RESULT_HASH
      
