name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  RESULT_HASH: hello

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: ch1
      id: ch1
      run:  |
        RESULT=$(git rev-parse --short HEAD)
        echo $RESULT
        echo "::set-output name=result_hash::$(echo $RESULT)"
    - name: ch2
      run:  |
        echo ${{steps.ch1.outputs.result_hash}}
      
