name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      RESULT_HASH: hello
    steps:
    - uses: actions/checkout@v3
    - name: ch1
      run:  |
        RESULT=$(git rev-parse --short HEAD)
        echo $RESULT
        ${{ jobs.env.RESULT_HASH: $RESULT }}
    - name: ch2
      run:  |
        echo ${{ jobs.env.RESULT_HASH }}
      
